version: '3.8'

services:
  api:
    build: .
    container_name: sedekahje-api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/sedekahje
      - PORT=8000
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:8.0
    container_name: sedekahje-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local 